# Generated by Django 5.0.6 on 2024-06-15 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_position_alter_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='birhday',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
