# Generated by Django 5.0.6 on 2024-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_birthday_user_birhday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birhday',
        ),
        migrations.AddField(
            model_name='user',
            name='birеhday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
