# Generated by Django 5.0.6 on 2024-06-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_birhday_user_birеhday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birеhday',
            new_name='birthday',
        ),
    ]
