# Generated by Django 5.0.6 on 2024-06-18 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=128, null=True, verbose_name='Диагноз')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_results', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_results', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='patients/results', verbose_name='Снимок')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.analysisresult')),
            ],
        ),
    ]
